### ISSUE TITLE
What would make an epic and awesome functional programming / F# side track for you?

### ISSUE THREAD

**Issue by Adron** [dotnetfringe/dotnetfringe.github.io#61]
@Krzysztof-Cieslak @lenadroid @tpetricek @dsyme @panesofglass @tugberkugurlu @sergey-tihon @pezipink @isaacabraham @ReedCopsey @rachelreese @mathias-brandewinder what would you all like to see?

**Comment by Krzysztof-Cieslak** [comment]
Just some random ideas (in random order):
1. F# OSS discussion panel - Tomas, Steffen, etc. (there is enough people doing F# OSS to choose nice lineup for something like that) (don't record it so people can be less... diplomatic than usually ;) )
2. Some more advanced F# talks - too often all F# talks on conferences are intro / beginner level, and there is enough people doing more crazy stuff with F#. I'd like to see next crazy TP talk by Ross, some crazy things you can do with CExpresions ( by Jared ?), or how to create VSCode extension using F# (:just_kidding:)
3. _New_ talks - that's probably problem with me as I'm just watching everything what is online but I'd like to see more new talks, not just repeating stuff that was presented before on other conferences.
4. "Cage match" with F# vs C# - 2 devs, 2 laptops, 2 languages, same questions / tasks. (Ofc, all in light-hearted manner) 
5.  Functional Programming Lab Hour - Mathias organized something like that during NDC London this year - basically each day instead of one talk we get all FP track speakers in one room and people could come, ask questions, do coding demos in small groups etc. All was driven more by people coming than by speakers - so we were talking / showing things people wanted. 
6. Goswin talk - stuff he has shown on FSharpConf was just mind-blowing and amazing.

Pinging people I've mentioned that was not pinged before: @forki @cloudRoutine @gwinsky

**Comment by mathias-brandewinder** [comment]
I can interpret the questions in a couple of ways: what would I personally want to see as an attendee, vs. what I think attendees to .NET Fringe would enjoy. Going to go for 2.

I think what is good is a mix of practical talks focusing on what you can do / real world examples (instead of telling me that FP is great, show me stuff you did with it - code/results speak for themselves), and a couple inspirational one, like Goswin's talk mentioned above. In that category, Darren Platt, based in SF, is great (compiling genetics DSL to actual DNA using F#).

From a conference standpoint, you probably want a couple 'recognizable names', and a couple lesser known ones.

I really, really liked what we did at NDC London this year with the FP lab hour. The idea was 'here is a room, all the FP speakers will be there, if you have questions bring them in and we will chat and pair code'. This worked great because lots of times people have questions that don't fit in the Q&A section format, and can best be answered by firing up a laptop. Personally, I care moderately about talks at conferences, and a chance to interact with speakers / attendees is something I really enjoy :) It's nice for attendees too, makes it much easier to talk to someone you might otherwise be too intimidated to approach.

Going to think about this some more. I might even disagree with myself in a couple of hours :)

Also, is that input useful, or answering a question different than the one you had in mind?

**Comment by Adron** [comment]
@Krzysztof-Cieslak excellent suggestions! I like them. Thanks for including @forki @cloudRoutine @gwinsky on the thread!

Loved the cage match idea, love it a lot. I'm going to think on it and might even introduce it into the .NET Fringe line up.  \m/

@mathias-brandewinder both 1 and 2 viewpoints are applicable to answer from. :+1: 

I dig the lab hour idea. This could be something we do.

Keep the suggestions coming everybody, and if you do know anyone else that would be interested in contributing a comment or two please include them in the thread!

**Comment by goswinr** [comment]
I am glad my talk was so well received. I ll be happy to do it again. I would love to show it with an open scource F# editor in Rhino. The development on Tsunami is not open and has kind of stopped. Anyone up for helping me with that?

**Comment by SeanKilleen** [comment]
I'd absolutely love to see a talk where someone takes a gnarly, complex domain and walks through modeling it with F#. Admittedly this is probably more beginner than folks would want to see, but I'd love a presentation on how to think functionally. I feel like even though I'm beginning to understand some functional concepts, I still think of things in C# first and then try to convert them to F#. How to I get my brain to a point where it's modeling functionally first? Help making that leap would be appreciated.

**Comment by ghost** [comment]
Going through side-by-side design of a functional real-world F# program and a similar OO based C# program, touching topics like modularity, use of classes vs functions, testing etc.

**Comment by WilliamBerryiii** [comment]
I'd love to see a lab hour or several hours ... maybe small group or office hour style with a focus more on the language than on just FP.

**Comment by Adron** [comment]
btw - thanks all for the comments and ideas. I'll be aiming to roll these together into a "functional coders week", "functional programming hackers weekend" or something in the near future AND am going to try to put something functional related together for .NET Fringe per the above suggestions!  👍 

So stay tuned and we'll tweet/blog/write it up when we get it finalized more!

Cheers! 

oh... and feel free to keep commenting with ideas btw. By no means is the thread closed.  :)
